backend/modules/useradmin/controllers/BusinessController.php
<?php

namespace backend\modules\useradmin\controllers;

use common\models\Facility;
use common\models\Photo;
use Yii;
use common\models\Room;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
/**
 * BusinessController implements the CRUD actions for Room model.
 */
class BusinessController extends Controller
{
    //public $layout='ex.php';
    public $enableCsrfValidation = false;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['update', 'create','index','view','create_pic','picdelete'],

                'rules' => [
                    [
                        'actions' => ['update','index','create','delete','view','create_pic','picdelete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'picdelete' => ['get','post'],
                    'update' => ['get', 'put', 'post'],
                ],
            ],
        ];
    }
    /*public function actions(){
        return [
            'upload' => [
                'class' => 'common\widgets\ueditor\UEditorAction',
                'config' => [

                    "imageUrlPrefix"  => "http://www.baidu.com",//图片访问路径前缀
                    "imagePathFormat" => "/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}" //上传保存路径
                ],
            ]
        ];

    }*/
    /*public function beforeAction()
    {
        //var_dump(Yii::$app->request->post());die();
        $model = Room::findOne(73);
        //$model = $this->findModel($id);
        //$model = new Photo();
        // $model->album_id = $id;
        $model->scenario = 'pic';
        if (Yii::$app->request->isPost ){
            echo "cvch";die();
            $model->upload();
            //return $this->redirect(['view', 'id' => $model->id]);
        }else {
            return $this->render('create_pic', [
                'model' => $model,
            ]);
        }
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
    }*/
    public function actions()
    {
        return [
            'upload'=>[
                'class' => 'common\widgets\file_upload\UploadAction',     //这里扩展地址别写错
                'config' => [
                    'imagePathFormat' =>"/images/upload/{yyyy}{mm}{dd}/{time}{rand:6}",
                ]
            ]
        ];
    }

    /**
     * Lists all Room models.
     * @return mixed
     */
    public function actionIndex()
    {

        $dataProvider = new ActiveDataProvider([
            'query' => Room::find()->where(['user_id' => Yii::$app->user->identity->id]),
            'pagination' => [
                'pageSize' => 20,
            ],
            'sort' => [
                'defaultOrder' => [
                    'createtime' => SORT_DESC,
                    'id' => SORT_NUMERIC,
                ]
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Room model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Room model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Room();

        $model->user_id = Yii::$app->user->identity->id;
        $facility = new Facility();

        if(Yii::$app->request->isPost){
            $data = Yii::$app->request->post();
            //$data["Room"]['facility']= json_encode($data["Room"]['facility']);


            //var_dump($data["Room"]);

            if ($model->load($data) && $facility->load($data) ){
                $isValid = $model->validate();
                $isValid = $facility->validate() && $isValid;
                if ($isValid) {
                    $model->save(false);
                    $facility->save(false);

                    return $this->redirect(['create_pic', 'id' => $model->id]);
                }

            }else{
                echo "failed";
            }
        }
       /* if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['create_pic', 'id' => $model->id]);
        }*/
        else {
            //return $this->redirect(['create_pic', 'id' => $model->id]);
            return $this->render('create', [
                'model' => $model,
                'facility' => $facility,
            ]);
        }
    }
    /**
     * 上传图片到相册
     * @param integer $id 相册ID
     */
    public function actionCreate_pic($id){
        $model = Room::findOne($id);
        //$model = $this->findModel($id);
        //$model = new Photo();
       // $model->album_id = $id;
        $model->scenario = 'pic';
        if (Yii::$app->request->isPost ){
            //echo "cvch";die();
            $picinfo = $model->upload();  //房屋相册上传
            //$p1[$i] = $imageUrl;
            //$p2[$i] = ['url' => $url, 'key' => $key];
            echo json_encode([
                'initialPreview' => $picinfo['Preview'],
                'initialPreviewConfig' => $picinfo['Config'],
                'append' => true,
            ]);
            return;
            //return $this->redirect(['view', 'id' => $model->id]);
        }else {
            return $this->render('create_pic', [
                'model' => $model,
            ]);
        }
    }


    /**
     * Updates an existing Room model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $facility = new Facility();  //家具设施
        $facility->room_id = $id;

        if(Yii::$app->request->isPost){
            $data = Yii::$app->request->post();

            //$data["Room"]['facility']= json_encode($data["Room"]['facility']);
            //var_dump($data["Room"]);
            if ($model->load($data)  ){
                $isValid = $model->validate();
                //$isValid = $facility->validate() && $isValid;
                if ($isValid) {
                    $model->save(false);
                    $facility->facility = Yii::$app->request->post('Facility')['facility'];
                    //var_dump($facility->facility);die();
                    $facility->roomFacilitySave($id);

                    return $this->redirect(['index']);
                }

            } else {
                $facility->facility['facility'] = $facility->find()
                    ->select(['child'])
                    ->where(['room_id'=>$id])->all();
                //var_dump($facility->facility['facility']);die();
                //$model->facility= json_decode($model->facility);

                return $this->render('update', [
                    'model' => $model,
                    'facility' => $facility,
                ]);
            }
        }else {
            //$model->facility= json_decode($model->facility);
            $arr = $facility->find()
                ->select(['child'])
                ->where(['room_id'=>$id])->asArray()->all();
            foreach($arr as $a){
                $facility->facility[] = $a['child'];
            }

            //var_dump($facility->facility['facility']);die();
            //$facility->facility =['空调','热水'];
            return $this->render('update', [
                'model' => $model,
                'facility' => $facility,
            ]);
        }
    }

    /**
     * Deletes an existing Room model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {

        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Room model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Room the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Room::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    public function actionPicdelete()
    {
        $id = Yii::$app->request->post('key');

        $model = Photo::findOne($id);
        if ( $model->created_by === Yii::$app->user->id) {
            try {
                //unlink(Yii::getAlias('@web/uploads/user/') . $model->created_by . '/' . $model->store_name);//dirname(__FILE__)
                //unlink('uploads/user/'.$model->created_by . '/' . $model->savename);
                unlink( '.' .$model->savepath);
            } catch (Exception $e) {
                throw new ServerErrorHttpException('Internal Server Error');
            }
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            return ['success' => $model->delete()];
        } else {
            throw new ForbiddenHttpException('You are not allowed to perform this action.');
        }
    }
}

backend/modules/useradmin/views/business/_form.php
<?php
//namespace frontend\modules\useradmin\views\business ;
use yii\web\View;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\ActiveField;
use yii\helpers\Url;
use common\widgets\ueditor\UEditor;
//use common\widgets\webuploader\MultiImage;
//use iisns\webuploader\MultiImage;
use kartik\file\FileInput;
/* @var $this yii\web\View */
/* @var $model common\models\Room */
/* @var $form yii\widgets\ActiveForm */
//$this->registerJsFile('@web/kode/js/bootstrap-select/bootstrap-select.js',['depends'=>['frontend\assets\KodeAsset']]);
//$this->registerJsFile('@web/kode/js/bootstrap-toggle/bootstrap-toggle.min.js',['depends'=>['frontend\assets\KodeAsset']]);
//$this->registerJsFile('@web/kode/js/moment/moment.min.js',['depends'=>['frontend\assets\KodeAsset']]);

/*$this->registerCssFile('@web/media/css/select2_metro.css',[ 'depends'=> 'frontend\assets\MetronicAsset']);
$this->registerCssFile('@web/media/css/chosen.css',[ 'depends'=> 'frontend\assets\MetronicAsset']);
$this->registerJsFile('@web/media/js/chosen.jquery.min.js',['depends'=>['frontend\assets\MetronicAsset']]);
$this->registerJsFile('@web/media/js/select2.min.js',['depends'=>['frontend\assets\MetronicAsset']]);
$this->registerJsFile('@web/media/js/jquery.tagsinput.min.js',['depends'=>['frontend\assets\MetronicAsset']]);
$this->registerJsFile('@web/media/js/jquery.multi-select.js',['depends'=>['frontend\assets\MetronicAsset']]);

/*$this->registerJs("
        jQuery(document).ready(function() {

		   // initiate layout and plugins

		   App.init();

		   FormValidation.init();

		});",View::POS_END);
$template = '{label}<div class="col-sm-10">{input}</div>{error}{hint}';
*/
$template = '{label}<div class="col-sm-10">{input}{error}{hint}</div>';
$label = ['class'=>"col-sm-2 text-c control-label form-label"];

?>

<div class="room-form form-horizontal">

    <?php $form = ActiveForm::begin([
        'options' => ['enctype'=>'multipart/form-data'],
    ]); /*$form->options['id']='form-horizontal'; *//* var_dump($form->options);die();*/ ?>

    <?= $form->field($model, 'title',['template' => $template])->textInput(['maxlength' => true,'class'=>"form-control md-input"])->label(null,$label) ?>

    <?= $form->field($model, 'price',['template' => $template])->input('number',['class'=>"form-control sm-input"])->label(null,$label) ?>


    <?= $form->field($model, 'connect',['template' => $template])->textInput(['maxlength' => true,'class'=>"form-control sm-input "])->label(null,$label) ?>

    <?= $form->field($model, 'atrribute',['template' => $template])->dropDownList(['单间/套一'=>'单间/套一','独栋'=>'独栋','套二'=>'套二','套三'=>'套三','套四'=>'套四','套五'=>'套五'],['class'=>"form-control select2-container span3"])->label(null,$label) ?>
    <?= $form->field($model, 'toilet',['template' => $template])->dropDownList(['独卫'=>'独卫','共卫'=>'共卫'],['class'=>"form-control select2-container span3"])->label(null,$label) ?>
    <?= $form->field($model, 'kitchen',['template' => $template])->dropDownList(['有'=>'有','无'=>'无'],['class'=>"form-control select2-container span3"])->label(null,$label) ?>

    <?= $form->field($model, 'area',['template' => $template])->input('number',['class'=>"form-control sm-input"])->label(null,$label) ?>
    <?= $form->field($model, 'address',['template' => $template])->textInput(['maxlength' => true,'class'=>"form-control md-input "])->label(null,$label) ?>

    <?php echo $form->field($facility, 'facility[]',['template' => $template])->checkBoxList(
        ['空调'=>'空调','热水'=>'热水','网络'=>'网络','衣柜'=>'衣柜','电梯'=>'电梯','向阳'=>'向阳'],
        ['class'=>'icheckbox_flat-green checked',])
        ->label(null,['class'=>"col-sm-2 control-label form-label "]) ?>

    <?= $form->field($model, 'userlimit',['template' => $template])->input('number',['class'=>"form-control sm-input"])->label(null,$label) ?>

    <?= $form->field($model, 'pay',['template' => $template])->dropDownList(['面议'=>'面议','押一付一'=>'押一付一','押一付二'=>'押一付二','押一付三'=>'押一付三'],['class'=>"select2-container span3"])->label(null,$label) ?>

    <?= $form->field($model, 'content',['template' => $template,])->label(null,$label)->widget(UEditor::className(),['class'=>'col-sm-10 form-control uedite-warp','id'=>'content','name'=>'content',])  ?>


        <div class="fileupload fileupload-new" data-provides="fileupload">
            <?= $form->field($model, 'pic',['template' => $template])->widget('common\widgets\file_upload\FileUpload',[
                'config'=>[]
            ])->label(null,$label) ?>

        </div>


    <!--<div class="form-actions">

        <button type="submit" class="btn green">Validate</button>

        <button type="button" class="btn">Cancel</button>

    </div>-->
    <div class="form-actions">
        <?= Html::submitButton($model->isNewRecord ? '创建' : '保存', ['class' => $model->isNewRecord ? 'btn btn-success green' : 'btn btn-primary green']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/useradmin/views/business/_form_update.php
<?php
//namespace frontend\modules\useradmin\views\business ;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\ActiveField;
use yii\captcha\Captcha;
use common\widgets\ueditor\UEditor;
use common\widgets\webuploader\MultiImage;
use yii\helpers\Url;
//use iisns\webuploader\MultiImage;
use shiyang\masonry\Masonry;
use kartik\file\FileInput;
/* @var $this yii\web\View */
/* @var $model common\models\Room */
/* @var $form yii\widgets\ActiveForm */
$template = '{label}<div class="col-sm-10">{input}{error}{hint}</div>';
$label = ['class'=>"col-sm-2 text-c control-label form-label"];
//$this->registerCssFile('@web/adminlte/plugins/iCheck/all.css',[ 'depends'=> 'backend\assets\AdminLteAsset']);
//$this->registerCssFile('@web/adminlte/plugins/iCheck/minimal/_all.css',[ 'depends'=> 'backend\assets\AdminLteAsset']);
//$this->registerJsFile('@web/adminlte/plugins/iCheck/icheck.js',[ 'depends'=> 'backend\assets\AdminLteAsset']);



?>

<div class="room-form form-horizontal">
    <?php $form = ActiveForm::begin([
        'options' => ['enctype'=>'multipart/form-data'],
    ]); /*$form->options['id']='form-horizontal'; *//* var_dump($form->options);die();*/ ?>
    <?= $form->field($model, 'title',['template' => $template])->textInput(['maxlength' => true,'class'=>"form-control md-input"])->label(null,$label)  ?>

    <?= $form->field($model, 'price',['template' => $template])->input('number',['class'=>"form-control sm-input"])->label(null,$label) ?>


    <?= $form->field($model, 'connect',['template' => $template])->textInput(['maxlength' => true,'class'=>"form-control sm-input "])->label(null,$label) ?>

    <?= $form->field($model, 'atrribute',['template' => $template])->dropDownList(['单间/套一'=>'单间/套一','独栋'=>'独栋','套二'=>'套二','套三'=>'套三','套四'=>'套四','套五'=>'套五'],['class'=>"form-control select2-container span3"])->label(null,$label) ?>
    <?= $form->field($model, 'toilet',['template' => $template])->dropDownList(['独卫'=>'独卫','共卫'=>'共卫','二卫'=>'二卫'],['class'=>"form-control select2-container span3"])->label(null,$label) ?>
    <?= $form->field($model, 'kitchen',['template' => $template])->dropDownList(['有'=>'有','无'=>'无'],['class'=>"form-control select2-container span3"])->label(null,$label) ?>

    <?= $form->field($model, 'area',['template' => $template])->input('number',['class'=>"form-control sm-input"])->label(null,$label) ?>
    <?= $form->field($model, 'address',['template' => $template])->textInput(['maxlength' => true,'class'=>"form-control md-input "])->label(null,$label) ?>

    <?php echo $form->field($facility, 'facility',['template' => $template])->checkBoxList(
        ['空调'=>'空调','热水'=>'热水','网络'=>'网络','衣柜'=>'衣柜','电梯'=>'电梯','向阳'=>'向阳'],
        ['class'=>'  icheckbox_flat-green checked facility-lable',])
        ->label(null,['class'=>"col-sm-2 control-label form-label "]) ?>

    <?= $form->field($model, 'userlimit',['template' => $template])->input('number',['class'=>"form-control sm-input"])->label(null,$label) ?>
    <?= $form->field($model, 'pay',['template' => $template])->dropDownList(['面议'=>'面议','押一付一'=>'押一付一','押一付二'=>'押一付二','押一付三'=>'押一付三'],['class'=>"form-control  select2-container md-input"])->label(null,$label) ?>

    <?= $form->field($model, 'content',['template' => '{label}<div class="col-md-7 col-sm-12">{input}{error}{hint}</div>'])->label(null,$label)->widget(UEditor::className(),['class'=>'col-md-7 form-control','id'=>'content','name'=>'content', ])  ?>

    <?= $form->field($model, 'pic',['template' => $template])->widget('common\widgets\file_upload\FileUpload',[
        'config'=>[]
    ])->label(null, ['class' => 'col-sm-2 control-label']) ?>


    <div class="row">
        <div class=" col-md-offset-1  col-md-10  col-sm-12 ">
        <?php
        $p1 = $p2 = [];
        foreach ($model->photos['photos'] as  $k => $v) {
            $p1[$k] = $v['savepath'];
            $p2[$k] = ['url' => '/useradmin/business/picdelete', 'key' => $v['id']];
        }
        echo $form->field($model, 'ext')->label('房间相册')->widget(FileInput::classname(), [
            'options' => ['multiple' => true],
            'pluginOptions' => [
                // 需要预览的文件格式
                'previewFileType' => 'image',
                // 预览的文件
                'initialPreview' => $p1,
                // 需要展示的图片设置，比如图片的宽度等
                'initialPreviewConfig' => $p2,
                // 是否展示预览图
                'initialPreviewAsData' => true,
                // 异步上传的接口地址设置
                'uploadUrl' => Url::toRoute(['/useradmin/business/create_pic?id='.$model->id]),
                // 异步上传需要携带的其他参数，比如商品id等
                'uploadExtraData' => [
                    'id' => $model->id,
                ],
                'uploadAsync' => true,
                // 最少上传的文件个数限制
                'minFileCount' => 1,
                // 最多上传的文件个数限制
                'maxFileCount' => 10,
                // 是否显示移除按钮，指input上面的移除按钮，非具体图片上的移除按钮
                'showRemove' => true,
                // 是否显示上传按钮，指input上面的上传按钮，非具体图片上的上传按钮
                'showUpload' => true,
                //是否显示[选择]按钮,指input上面的[选择]按钮,非具体图片上的上传按钮
                'showBrowse' => true,
                // 展示图片区域是否可点击选择多文件
                'browseOnZoneClick' => true,
                // 如果要设置具体图片上的移除、上传和展示按钮，需要设置该选项
                'fileActionSettings' => [
                    // 设置具体图片的查看属性为false,默认为true
                   // 'showZoom' => false,
                    // 设置具体图片的上传属性为true,默认为true
                    'showUpload' => true,
                    // 设置具体图片的移除属性为true,默认为true
                    'showRemove' => true,
                ],
            ],
            // 一些事件行为
            /*'pluginEvents' => [
                // 上传成功后的回调方法，需要的可查看data后再做具体操作，一般不需要设置
                "fileuploaded" => "function (event, data, id, index) {
                console.log(data);
            }",
            ],*/
        ]);
        ?>

        </div>
    </div>
<script>
    /*$(document).ready(function(){
        $(".room-form").click(function(){
            alert('haha');
        });
    });*/

  /*  $(document).ready(function(){

        $(".img-edit").click(function(event){
            alert('haha');
        });

    });*/
</script>



    <!--<div class="form-actions">

        <button type="submit" class="btn green">Validate</button>

        <button type="button" class="btn">Cancel</button>

    </div>-->
    <div class="form-actions">
        <?= Html::submitButton($model->isNewRecord ? '创建' : '保存', ['class' => $model->isNewRecord ? 'btn btn-success green' : 'btn btn-primary green']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/useradmin/views/business/business.php
<?php
/* @var $this yii\web\View */
?>
<h1>business/business</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

backend/modules/useradmin/views/business/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\web\View;
use yii\data\Pagination;
use backend\widgets\common\LinkPages;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '出租房管理台';
$this->params['breadcrumbs'][] = '房东';
$this->params['breadcrumbs'][] =  $this->title;
//$this->registerCssFile('@web/ex/js/advanced-datatable/css/demo_page.css',[]);
//$this->registerCssFile('@web/ex/js/advanced-datatable/css/demo_table.css',[]);
//$this->registerCssFile('@web/ex/js/data-tables/DT_bootstrap.css',[]);
//$this->registerCssFile('@web/media/css/DT_bootstrap.css',[ 'depends'=> 'frontend\assets\MetronicAsset']);
//$this->registerJsFile('@web/media/js/select2.min.js',['depends'=>['frontend\assets\MetronicAsset']]);
//$this->registerJsFile('@web/media/js/jquery.dataTables.min.js',['depends'=>['frontend\assets\MetronicAsset']]);
//$this->registerJsFile('@web/media/js/DT_bootstrap.js',['depends'=>['frontend\assets\MetronicAsset']]);
//$this->registerJsFile('@web/ex/js/advanced-datatable/js/jquery.dataTables.js',['depends'=>['backend\assets\AdminLteAsset']]);
//$this->registerJsFile('@web/ex/js/data-tables/DT_bootstrap.js',['depends'=>['backend\assets\AdminLteAsset']]);
//$this->registerJsFile('@web/ex/js/dynamic_table_init.js',['depends'=>['backend\assets\AdminLteAsset']]);


$data = $dataProvider->getModels();
$count = $dataProvider->getCount();
$pages = new Pagination(['totalCount' => $count, 'pageSize' => 18]);
?>
<div class="row">
<div class="col-md-12 ">

    <div class="box">
        <div class="box-body">
            <a class="btn btn-app blue-btn">
                <i class="fa fa-edit"></i> 长租
            </a>
            <a class="btn btn-app blue-btn">
                <i class="fa fa-edit"></i> 短租
            </a>

            <a class="btn btn-app blue-btn">
                <i class="fa fa-save"></i> 设置
            </a>
            <a class="btn btn-app blue-btn">
                <span class="badge bg-yellow">3</span>
                <i class="fa fa-bullhorn"></i> 日志
            </a>

            <a class="btn btn-app blue-btn">
                <span class="badge bg-purple">891</span>
                <i class="fa fa-users"></i> 房客
            </a>

            <a class="btn btn-app blue-btn">
                <span class="badge bg-aqua">12</span>
                <i class="fa fa-envelope"></i> 消息
            </a>
            <a class="btn btn-app blue-btn">

                <i class="fa fa-heart-o"></i> 帮助
            </a>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- Start Quick Menu -->
    <!-- End Quick Menu -->

</div>
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <div class="btn-group">
                    <a href='<?= Url::toRoute('business/create') ?>' id="btn editable-sample_new" class="btn btn-primary">
                        <i class="fa fa-plus"></i> 新 增
                    </a>
                </div>

                <div class="box-tools">
                    <div class="input-group input-group-sm" style="width: 300px;top: 6px;">
                        <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </div>

            </div>

            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <thead >
                    <tr role="row" style="font-size: 14px;">


                        <th>
                            <a href="<?= \yii\helpers\Url::current(['sort' => (Yii::$app->request->get('sort') == 'status') ? '-status' : 'status']) ?>">状态</a>
                        </th>


                        <th ><a href="<?= \yii\helpers\Url::current(['sort' => 'title']) ?>">标题</a></th>

                        <th><a
                                href="<?= \yii\helpers\Url::current(['sort' => (Yii::$app->request->get('sort') == 'price') ? '-price' : 'price']) ?>">价格</a>
                        </th>

                        <th ><a
                                href="<?= \yii\helpers\Url::current(['sort' => (Yii::$app->request->get('sort') == 'createtime') ? '-createtime' : 'createtime']) ?>">起始时间</a>
                        </th>
                        <th class=""></th>


                        <!--
                            <th class="sorting_asc" tabindex="0" aria-controls="example0" rowspan="1" colspan="1"
                                aria-sort="ascending" aria-label="Name: activate to sort column descending"
                                style="width: 133px;">Name
                            </th>-->

                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($data as $list): ?>
                        <tr>

                            <td><?= ($list['status'] == 1) ? '出售中' : '已租' ?></td>

                            <td class="">
                                <a target="_blank" href="<?= Url::to('@web/room/view?id=' . $list['id']) ?>"><?= Html::encode($list['title']) ?></a>

                                <p>地址：<?= Html::encode($list['address']) ?></p></td>

                            <td ><?= Html::encode($list['price']) ?></td>

                            <td><?= Html:: encode((strtotime($list['createtime']) > 0) ? date('Y-m-d', strtotime($list['createtime'])) : '未设置') ?></td>


                            <td> <?= Html::a('修改', ['update', 'id' => $list['id']], ['class' => 'btn btn-default btn-xs']) ?>
                                <?= Html::a('删除', ['delete', 'id' => $list['id']], [
                                    'class' => 'btn btn-danger  btn-xs',
                                    'data' => [
                                        'confirm' => '确定要删除这条商品吗？',
                                        'method' => 'post',
                                    ],
                                ]) ?></td>

                            <!-- <td class="hidden-480" style="display: none">A</td>
                             <td class="hidden-480" style="display: none">A</td>
                             <td class="hidden-480" style="display: none">A</td>-->

                        </tr>
                    <?php endforeach; ?>

                    </tbody></table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>